import type { AuditCheck, AuditRequest, EvidenceLink, WorkspaceAudit } from './workspace-types';
export const testCheck = (overrides: Partial<AuditCheck> = {}): AuditCheck => ({
  id: 'c1',
  auditId: 'a1',
  controlKey: 'scope',
  controlRef: 'Scope',
  whatWasTested: 'Boundaries',
  whereToFind: 'Documents',
  result: null,
  notes: null,
  source: 'manual',
  derivedFrom: null,
  position: 0,
  updatedAt: '2026-09-30T10:00:00Z',
  reviewedAt: null,
  reviewedBy: null,
  requests: [],
  evidenceLinks: [],
  ...overrides,
});
export const testRequest = (overrides: Partial<AuditRequest> = {}): AuditRequest => ({
  id: 'r1',
  controlId: 'c1',
  question: 'Provide a sample',
  ownerMemberId: 'm1',
  dueDate: '2026-09-29',
  status: 'open',
  createdBy: 'Auditor',
  createdAt: '2026-09-28T10:00:00Z',
  updatedAt: '2026-09-30T10:00:00Z',
  messages: [],
  ...overrides,
});
export const testAudit = (controls: AuditCheck[]): WorkspaceAudit => ({
  id: 'a1',
  reference: 'IA-01',
  scope: 'ISMS',
  criteria: 'Policies',
  auditorName: 'Auditor',
  plannedStartDate: null,
  plannedEndDate: null,
  status: 'in_progress',
  conclusionVerdict: 'conform',
  conclusionNotes: 'Sample supports the conclusion.',
  signoffAuditorName: null,
  signoffAuditorDate: null,
  signoffSpoName: null,
  signoffSpoDate: null,
  signoffTopMgmtName: null,
  signoffTopMgmtDate: null,
  position: 0,
  controls,
  findings: [],
  documentId: 'd1',
  document: { id: 'd1', status: 'draft' },
  updatedAt: '2026-09-30T10:00:00Z',
});

export const testEvidence = (overrides: Partial<EvidenceLink> = {}): EvidenceLink => ({
  id: 'e1',
  controlId: 'c1',
  sourceType: 'document',
  sourceId: 'd1',
  title: 'Scope',
  versionLabel: 'v2',
  snapshot: { content: 'Retained text' },
  capturedBy: 'Owner',
  createdAt: '2026-09-30T12:00:00Z',
  ...overrides,
});
